name: test-build
on:
  push:
    paths:
      - 'src/**'
      - 'build.gradle'
      - 'bungee/src/**'
      - 'bungee/build.gradle'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Get Short Identifier
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - name: Build
        id: build
        env:
          VERSION_IDENTIFIER: SNAPSHOT+${{ steps.short-sha.outputs.sha }}
        run: ./gradlew :build :githubActionOutput --stacktrace
      - name: Build Bungee
        id: build_bungee
        env:
          VERSION_IDENTIFIER: SNAPSHOT+${{ steps.short-sha.outputs.sha }}
        run: ./gradlew :bungee:build :bungee:githubActionOutput --stacktrace
      - name: GitHub Action Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.build.outputs.artifact_name }}
          path: ${{ steps.build.outputs.artifact_path }}
      - name: GitHub Action Bungee Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.build_bungee.outputs.artifact_name }}
          path: ${{ steps.build_bungee.outputs.artifact_path }}
